Improve curl detection.
In some old versions of curl the option --help gives exit code 2 making
our test fail.

diff --git a/authy-ssh b/authy-ssh
--- a/authy-ssh
+++ b/authy-ssh
@@ -41,12 +41,19 @@ function require_root() {
 }
 
 function require_curl() {
+    which curl 2>&1 > /dev/null
+    if [ $? -eq 0 ]
+    then
+      return 0
+    fi
+
+    # if `which` is not installed this check is ran
     curl --help 2>&1 > /dev/null
 
     if [ $? -ne 0 ]
     then
         red "install curl and try again"
-        run_shell
+        run_shell # start the shell if all checks failed.
     fi
 }
 
