Add support for a grace time period, so that two-factor authentication is not required if a successful login was completed recently

diff --git a/authy-ssh b/authy-ssh
--- a/authy-ssh
+++ b/authy-ssh
@@ -4,6 +4,8 @@ VERSION="1.4"
 AUTHY_URL="https://api.authy.com"
 APP_ROOT=`dirname $0`
 CONFIG_FILE="$APP_ROOT/authy-ssh.conf"
+LAST_LOGIN_FOLDER="$HOME/.authy-ssh/"
+LAST_LOGIN_FILE="$LAST_LOGIN_FOLDER/last-login"
 UPSTREAM_URL="https://raw.github.com/authy/authy-ssh/master/authy-ssh"
 READ_TIMEOUT=60
 
@@ -40,7 +42,7 @@ function escape_input() {
 }
 
 function escape_number() {
-  sed 's/[^0-9]*//g' <<< $*
+  sed 's/^-?[0-9]*//g' <<< $*
 }
 
 function read_input() {
@@ -51,6 +53,19 @@ function read_input() {
 function read_number() {
   read -t "$READ_TIMEOUT" number
   echo "$(escape_number $number)"
+}
+
+function get_date() {
+  echo "$(date +%s)"
+}
+
+function update_last_login() {
+  mkdir -p "$LAST_LOGIN_FOLDER"
+  echo "$USER|$(get_date)|$(get_ssh_client_ip)" > $LAST_LOGIN_FILE
+}
+
+function get_ssh_client_ip() {
+  echo "$(echo $SSH_CLIENT | awk '{ print $1}')"
 }
 
 function require_root() {
@@ -183,16 +198,20 @@ function install_authy() {
 
     if [[ $SUDO_USER ]]
     then
-      green "   sudo ${dest} enable $SUDO_USER <your-email> <your-numeric-country-code> <your-cellphone>"
-      green "   Example: sudo $0 enable $SUDO_USER myuser@example.com 1 401-390-9987"
+      green "   sudo ${dest} enable $SUDO_USER <your-email> <your-numeric-country-code> <your-cellphone> [grace-period]"
+      green "   Example: sudo $0 enable $SUDO_USER myuser@example.com 1 401-390-9987 -1"
     else
-      green "   sudo ${dest} enable $USER <your-email> <your-numeric-country-code> <your-cellphone>"
-      green "   Example: sudo $0 enable $USER myuser@example.com 1 401-390-9987"
+      green "   sudo ${dest} enable $USER <your-email> <your-numeric-country-code> <your-cellphone> [grace-period]"
+      green "   Example: sudo $0 enable $USER myuser@example.com 1 401-390-9987 -1"
     fi
     echo ""
     echo "To enable two-factor authentication on user account type: "
     echo ""
-    green "   sudo ${dest} enable <local-username> <user-email> <user-cellphone-country-code> <user-cellphone>"
+    green "   sudo ${dest} enable <local-username> <user-email> <user-cellphone-country-code> <user-cellphone> [grace-period]"
+    echo ""
+    echo "Where grace-period, optionally, specify the number of seconds two-factor authentication will not be"
+    echo "  required for creating a new session, after a successful login, from the same user and IP address."
+    echo "  Using the value of -1 will always require two-factor authentication and is the default if not specified."
     echo ""
     echo "To uninstall Authy SSH type:"
     echo ""
@@ -261,6 +280,46 @@ function check_api_key() {
     return $OK
 }
 
+function check_grace_period() {
+    # check if we have a last login file
+    if [[ -f "$LAST_LOGIN_FILE" ]]
+    then
+        # read in the last_login file, don't use colons: ipv6!
+        IFS="|"; declare -a last_login=($(head -n 1 "$LAST_LOGIN_FILE"))
+        # if the user in the file is current user and the IP matches
+        if [[ ${last_login[0]} == $USER && ${last_login[2]} == $(get_ssh_client_ip) ]]
+        then
+            grace_period="$(escape_number "$1")"
+            
+            # if grace_period not sent in by key
+            if [ -z $grace_period ]
+            then
+                # read in the user config
+                for user in `read_config user`
+                do
+                    IFS=":"; declare -a authy_user=($user)
+                    # for this user, check if it has a grace period
+                    if [[ ${authy_user[0]} == $USER && ${#authy_user[@]} -gt 2 && $(escape_number ${authy_user[2]}) -gt -1 ]]
+                    then
+                        grace_period="$(escape_number ${authy_user[2]})"
+                    fi
+                done        
+            fi
+
+            # once we have grace period
+            if [ ! -z $grace_period ]
+            then
+                # if last login time plus grace period is less than current time
+                if [[ $(($(escape_number ${last_login[1]}) + $grace_period)) -ge $(escape_number $(get_date)) ]]
+                then
+                    return $OK
+                fi
+            fi            
+        fi        
+    fi
+    return $FAIL
+}
+
 # Usage: $(read_config banner)
 function read_config() {
     key="$1"
@@ -316,8 +375,20 @@ function protect_user() {
     then
       exit $FAIL
     fi
+    
+    echo -n "Enter your desired grace-period (in seconds) [-1]: "
+    read grace_period
+    
+    if [[ $grace_period == "" ]]
+    then
+        grace_period=-1
+    elif ! [[ $grace_period =~ ^(-1|[0-9]+)$ ]]
+    then
+        yellow "grace-period is invalid"
+        exit $FAIL
+    fi
 
-    echo "command=\"$COMMAND login $authy_user_id\" $ssh_key" >> "${auth_keys}"
+    echo "command=\"$COMMAND login $authy_user_id $grace_period\" $ssh_key" >> "${auth_keys}"
     if [[ $(whoami) == "root" ]]
     then
       chown "$local_user" "$auth_keys"
@@ -325,7 +396,7 @@ function protect_user() {
     green "The user is now protected with authy"
 }
 
-# usage: register_user "local_user" "<email>" "<country-code>" "<cellphone>"
+# usage: register_user "local_user" "<email>" "<country-code>" "<cellphone>" "<grace-period>"
 function register_user() {
   register_user_on_authy $*
 
@@ -334,9 +405,19 @@ function register_user() {
       exit $FAIL
   fi
 
-  if [[ $authy_user_id ]]
+  grace_period="$(escape_number $5)"
+  if [ -z $grace_period ]
   then
-      echo "user=$local_user:$authy_user_id" >> $CONFIG_FILE
+      grace_period=-1
+  elif ! [[ $grace_period =~ ^(-1|[0-9]+)$ ]]
+  then
+      yellow "grace-period is invalid"
+      exit $FAIL
+  fi
+  
+  if [[ $authy_user_id && $grace_period ]]
+  then
+      echo "user=$local_user:$authy_user_id:$grace_period" >> $CONFIG_FILE
       green "User was registered"
   else
       red "Cannot register user: $response"
@@ -518,6 +599,8 @@ function login() {
             fi
         fi
 
+        update_last_login
+        
         if [[ $mode != "test" ]]
         then
             run_shell
@@ -554,6 +637,7 @@ function request_sms() {
 function ask_token_and_log_user_in() {
     mode="$(escape_input $1)"
     authy_id="$(escape_number $2)"
+    grace_period="$(escape_number $3)"
 
     if [[ $authy_id == "" ]]
     then
@@ -577,6 +661,14 @@ function ask_token_and_log_user_in() {
     if [[ $AUTHY_TOKEN ]] # env var
     then
       times=1
+    fi
+    
+    check_grace_period $grace_period
+    if [[ $? == $OK ]]
+    then
+      debug "Grace period allowed"
+      update_last_login
+      run_shell
     fi
 
     for i in `seq 1 $times`
@@ -653,13 +745,13 @@ case $1 in
         check_config_file "writable"
         AUTHY_API_KEY="$(read_config api_key)"
         check_api_key
-        register_user "$2" "$3" "$4" "$5"
+        register_user "$2" "$3" "$4" "$5" "$6"
         ;;
     login)
         check_config_file
         AUTHY_API_KEY="$(read_config api_key)"
         check_api_key
-        ask_token_and_log_user_in "login" "$2"
+        ask_token_and_log_user_in "login" "$2" "$3"
         ;;
     protect)
         check_config_file
@@ -699,9 +791,19 @@ Available commands:
     enable
         receives a list of arguments needed to register a user. usage:
 
-        sudo $0 enable [local-user] [email] [numeric country code] [cellphone]
+        sudo $0 enable [local-user] [email] [numeric country code] [cellphone] <grace period>
 
-        Example: sudo $0 enable myuser myuser@example.com 1 401-390-9987
+        Where grace-period, optionally, specifies the number of seconds two-factor authentication will not be
+        required for creating a new session, after a successful login, from the same user and IP address.
+        Using the value of -1 will always require two-factor authentication and is the default if not specified.
+
+        Always require two-factor authentication:
+
+        Example: sudo $0 enable myuser myuser@example.com 1 401-390-9987 -1
+
+        Allow 300 seconds after a successful login before requiring two-factor authentication again:
+
+        Example: sudo $0 enable myuser myuser@example.com 1 401-390-9987 300
 
     protect
         installs authy-ssh for the given user
